### ISSUE TITLE
Add support for .NET Core (or .NET 5)

### ISSUE THREAD

**Issue by vchelaru** [chris84948/AirspaceFixer#4]
Adding this nuget package to a .NET Core project requires using .NET Framework instead of .NET Core.

![image](https://user-images.githubusercontent.com/729631/148813784-88b5fdca-8d61-4bac-8e90-baec0241d35a.png)

This will continue to become a worse problem as more apps move off of .NET Framework 4.X

**Comment by chris84948** [comment]
I know this has been open for a while, but I just released v1.0.6 which adds .NET 6 compatibility. 

Hope it works for you!
